name: manually build ndk-pkg packages

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true
        default: zlib

      sdk-api-level:
        description: choose the min sdk api level to be built with
        type: choice
        options:
          - '33'
          - '32'
          - '31'
          - '30'
          - '29'
          - '28'
          - '27'
          - '26'
          - '25'
          - '24'
          - '23'
          - '22'
          - '21'

      target-abi:
        description: choose a target abi to be built for
        type: choice
        options:
          - arm64-v8a
          - armeabi-v7a
          - x86_64
          - x86

      build-type:
        description: choose a build type
        type: choice
        options:
          - release
          - debug

      link-type:
        description: choose a link type
        type: choice
        options:
          - static-only
          - static-prefered
          - shared-only
          - shared-prefered

      pack-type:
        description: choose a pack type
        type: choice
        options:
          - tar.xz
          - tar.lz
          - tar.gz
          - tar.bz2
          - zip

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

jobs:
  build:

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: ndk-pkg env
      - run: ndk-pkg setup
      - run: ndk-pkg sysinfo
      - run: ndk-pkg update
      - run: ndk-pkg install android-${{ github.event.inputs.sdk-api-level }}/${{ github.event.inputs.target-abi }}/${{ github.event.inputs.package-name }} --build-type=${{ github.event.inputs.build-type }} --link-type=${{ github.event.inputs.link-type }} ${{ github.event.inputs.log-level }}
      - run: ndk-pkg pack    android-${{ github.event.inputs.sdk-api-level }}/${{ github.event.inputs.target-abi }}/${{ github.event.inputs.package-name }} -o . -t ${{ github.event.inputs.pack-type }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.package-name }}-android${{ github.event.inputs.sdk-api-level }}-${{ github.event.inputs.target-abi }}
          path: ${{ github.event.inputs.package-name }}-*.${{ github.event.inputs.pack-type }}
